version: '3'

services:
  db:
    image: postgres:12-alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ../../db/data:/var/lib/postgresql/data/
    ports:
      -  54032:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    ports:
      -  ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    volumes:
      - pg-admin-data:/var/lib/pgadmin

volumes:
    pg-admin-data: